name: test11
favicon: null
layout_spectrum: 0.2978177818004042
typography_spectrum: 0.8275812030769885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.37349013634957373
  lightness: 0.002196838613599539
  saturation: 0.9759592371992767
  rhythmicContrast: 0.5742065897211432
purpose: []
